### ISSUE TITLE
Feature: Web Extension

### ISSUE THREAD

**Issue by TommasU** [fall2021-csc510-group40/filmfan#32]
Create a web plug-in extension
-extension is to provide a small search bar for faster search within the browser

**Comment by g-fringer** [comment]
A general UI has been developed for a Chrome extension, but the intricacies of gathering data dynamically are proving to be challenging. Plan to work on this tomorrow.

**Comment by g-fringer** [comment]
Basic version of the extension is complete, and currently in the review process to be published on the Chrome Extenstion store. A copy has been uploaded to the repository under the "chrome-extension" branch. To use and test:

* In Google Chrome, go to "chrome://extensions", and in the top right corner, click the switch to turn on "Developer Mode".
* Download the repository, and then click "Load Unpacked" in the top left corner. Navigate to the "Filmfan Search" folder in the repository, and then click "Select Folder" in the file explorer.
* This should display the Extension on the Extensions page, and after turning it on, it should be available for use.
